version: '3.8'

services:
  db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - MONGODB_URI=mongodb://db:27017/inventory
      - NODE_ENV=production
    depends_on:
      - db

  inventory-app:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  mongo_data:
